name: Build PicCap with hyperion-webos and create IPK

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TOOLCHAIN_URL: https://github.com/openlgtv/buildroot-nc4/releases/download/webos-d7ed7ee/arm-webos-linux-gnueabi_sdk-buildroot.tar.gz
  TOOLCHAIN_SHA256: 32816626e99fb34922a49d0c639f7c8a30356fffb222372d4823027f1382f640
  TOOLCHAIN_DIR: /opt/arm-webos-linux-gnueabi_sdk-buildroot
  TOOLCHAIN_FILE: /opt/arm-webos-linux-gnueabi_sdk-buildroot/share/buildroot/toolchainfile.cmake

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        
    - uses: actions/setup-node@v3
      with:
         node-version: 18

    - name: Install webOS CLI
      run: sudo npm install --location=global @webosose/ares-cli

    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: npm install

    - name: Download and unpack toolchain
      working-directory: /opt
      run: |
        wget -q -O toolchain.tar.gz ${TOOLCHAIN_URL}
        echo "${TOOLCHAIN_SHA256} toolchain.tar.gz"|sha256sum -c -
        tar xf toolchain.tar.gz

    - name: Relocate toolchain
      working-directory: ${{ env.TOOLCHAIN_DIR }}
      run: |
        ./relocate-sdk.sh

    - name: Check CMAKE Version
      run: which cmake && cmake --version

    - name: Build PicCap, hyperion-webos and copy files
      working-directory: ${{github.workspace}}
      run: npm run-script build-all

    - name: Package Frontend and Service
      run: npm run-script package

    - name: List files
      run: find . && find ./build

    - name: Upload PicCap IPK
      uses: actions/upload-artifact@v4
      with:
        name: piccap_ipk
        path: ./build/*.ipk

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./build/*.ipk
